name: Gripe
description: Describe a bug, problem, or annoyance that doesn't have a simple reproducer
labels: ["best effort"]
title: "[Gripe]: "
body:
  - type: markdown
    attributes:
      value: |
        * **** If you are able to define a minimal reproducer for the issue, please use a different issue type.**

        * ****  Gripes will be dealt with on a "best effort" basis only, and cannot be high priority.**

        * ****Multiple iterations may be necessary to understand your issue well enough to posit a remedy.**

  - type: textarea
    id: gripe-details
    attributes:
      label: Details
      placeholder: Please describe your issue in as much detail as possible
