#!/bin/bash

prog=${0##*/}

usage() {
    cat 1>&2 <<EOF
usage: $prog [-c <file-to-clean-up-prior-to-test>]+ <sql-input-file> <exec> [<exec-args>]
EOF
    exit ${1:-1}
}
while getopts :c: OPT; do
    case $OPT in
        c)
        rm -fv "$OPTARG"
        ;;
        *)
        usage 1
    esac
done
shift $[ OPTIND - 1 ]
# Invoke a database test reading the SQL from an input file.
if (( $# < 2 )); then
  usage 1
fi

sqlfile="$1"; shift
exec="$1"; shift

if ! [[ -r "$sqlfile" ]]; then
  echo "Specified SQL input file $sqlfile not readable." 1>&2
  exit 1
fi

exec "$exec" "$@" "`cat \"$sqlfile\"`"
