#!/bin/bash

[[ -n "$SRT_PUBLIC_CONTEXT" ]] || \
  { echo "NOvA software must be set up to run this script!" 1>&2; exit 1; }
ack --cpp -l include | \
xargs perl -wapi\~ -e 'use File::Basename;
my $srtpc = `cd \"$ENV{SRT_PUBLIC_CONTEXT}\" && /bin/pwd`;
chomp $srtpc;
if (m&^\s*#\s*include\s+["<]([^>"/]+)[>"]&) {
  my $include = ${1};
  my $package = `cd "\$(dirname \"$ARGV\")" && /bin/pwd`;
  chomp $package;
  $package =~ s&/(?:cxx/)?(?:inc|include|src)&&;
  $package =~ s&^\Q${srtpc}/\E&&;
  if ($include and $package and -f "${srtpc}/include/${package}/${include}") {
    print STDERR "Fixing include ${include} -> ${package}/${include} in $ARGV.\n";
    s&^(\s*#\s*include\s+["<])(\Q${include}\E[<"])&${1}${package}/${2}&;
  }
}'
