#!/usr/bin/perl -w

use strict;

use artRedmine;

my $api = artRedmine();

artRedmine::debug_print(*STDERR, $api->projects->project->get("art")->all());

artRedmine::debug_print(*STDERR, $api->get());

1;
