#!/usr/bin/perl -w
########################################################################
# filter-timetracker
#
# Original author: 2014/12/16 CHG.
#
# Pilfered from cetbuildtools/bin/filter-output
########################################################################
use strict;

while (<>) {
  # Several date-time formats.
  s&\d{4}-(?:0\d|1[0-2])-(?:[0-2]\d|3[01])T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:,\d+)?(Z[-+]?\d+)?&<date-time>&g;
  s&\d{4}-(?:0\d|1[0-2])-(?:[0-2]\d|3[01])(?:\s+(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?(?:\s+(?:[-+]\d+|[A-Z]{3}))?)?)?&<date-time> &g;
  s&\d+-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-\d{4}(?:\s+(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?(?:\s+(?:[-+]\d+|[A-Z]{3}))?)?)?&<date-time> &g;
  # TimeTracker summary lines
  s&\s+0[^\S\r\n]&<mem size>&g;
  s&\s*\d+\.\d+(e[+-]\d+)?[^\S\r\n]*&<mem size>&g;
  s&\s*\n&\n&g;
  print;
}
